# Generated by Django 3.0.6 on 2020-06-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=55)),
                ('phoneno', models.IntegerField(blank=True)),
                ('about', models.CharField(blank=True, max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
