# Generated by Django 3.0.6 on 2020-06-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnAuth', '0002_auto_20200613_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
