# Generated by Django 3.0.6 on 2020-06-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unAuth', '0005_auto_20200506_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
