# Generated by Django 3.0.6 on 2020-06-11 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UnAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=55)),
                ('document_url', models.CharField(max_length=55)),
                ('document_semester', models.IntegerField()),
                ('document_access_type', models.CharField(max_length=20)),
                ('document_year', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('document_ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UnAuth.User')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_label', models.CharField(max_length=66)),
                ('user_id', models.IntegerField()),
                ('notification_type', models.CharField(max_length=55)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Document')),
                ('notification_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UnAuth.User')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Document')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UnAuth.User')),
            ],
        ),
    ]
