# Generated by Django 3.0.6 on 2020-06-06 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unAuth', '0006_auto_20200606_0732'),
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('accessId', models.AutoField(primary_key=True, serialize=False)),
                ('documentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Document')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unAuth.User')),
            ],
        ),
    ]
