# Generated by Django 3.0.6 on 2020-06-06 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unAuth', '0006_auto_20200606_0732'),
        ('Auth', '0002_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notificationLabel', models.CharField(max_length=50)),
                ('notificationBy', models.CharField(max_length=50)),
                ('noificationType', models.CharField(max_length=1)),
                ('createDate', models.DateField(auto_now_add=True)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.Document')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unAuth.User')),
            ],
        ),
    ]
