# Generated by Django 3.0.6 on 2020-06-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_auto_20200606_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notificationLabel',
            field=models.CharField(max_length=256),
        ),
    ]
